// Generates host rule samples from migration/mapping.csv (plan §12 T7, §13).
//   node scripts/redirects.mjs          -> writes redirects/htaccess.sample,
//                                          redirects/_redirects, redirects/nginx.conf.sample
//   node scripts/redirects.mjs --check  -> exits 1 if the files are stale
// Only rows with decision move (301) or remove (410) produce rules. "keep"
// rows are served by the build itself; "pending" rows wait for an owner
// decision and deliberately produce no rule (they must not be guessed).
// These are samples: they are NOT copied into dist/ and must be verified on
// the real host (Apache/LiteSpeed vs nginx, TLS proxy) before going live.
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const ORIGIN = "https://www.cince-tercuman.com";
const WRITTEN = new Set(["/cince-ceviri/", "/web-sitenizi-cinceye-cevirin/"]);

export function parseCsv(text) {
  const rows = [];
  for (const line of text.split(/\r?\n/)) {
    if (!line.trim() || line.startsWith("#")) continue;
    const cells = [];
    let cur = "", q = false;
    for (let i = 0; i < line.length; i++) {
      const ch = line[i];
      if (q) {
        if (ch === '"' && line[i + 1] === '"') { cur += '"'; i++; }
        else if (ch === '"') q = false;
        else cur += ch;
      } else if (ch === '"') q = true;
      else if (ch === ",") { cells.push(cur); cur = ""; }
      else cur += ch;
    }
    cells.push(cur);
    rows.push(cells);
  }
  const [head, ...data] = rows;
  return data.map((r) => Object.fromEntries(head.map((h, i) => [h, r[i] ?? ""])));
}

export async function readMapping() {
  return parseCsv(await readFile(join(ROOT, "migration/mapping.csv"), "utf8"));
}

const reEsc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
const stripSlash = (p) => p.replace(/^\//, "").replace(/\/$/, "");

export function render(rows) {
  const moves = rows.filter((r) => r.decision === "move" && r.http_code === "301");
  const gone = rows.filter((r) => r.decision === "remove" && r.http_code === "410");
  const pending = rows.filter((r) => r.decision === "pending");
  const header = (c) => [
    `${c} GENERATED by scripts/redirects.mjs from migration/mapping.csv — do not edit by hand.`,
    `${c} Sample only: verify on the real host before going live (plan §12 T7, §13).`,
    `${c} Pending owner decisions (no rule yet): ${pending.map((r) => r.old_url).join(" ") || "none"}`
  ].join("\n");

  const apache = `${header("#")}
# Apache / LiteSpeed (.htaccess). Rename to .htaccess in the web root only after
# testing; if TLS is terminated by a proxy, replace the %{HTTPS} condition with
# the host's verified variable to avoid a redirect loop.
Options -MultiViews
DirectoryIndex index.html
RewriteEngine On

# 1) Old equivalents -> final HTTPS URL in a single 301 (also from http / bare host).
${moves.map((r) => `RewriteRule ^${reEsc(stripSlash(r.old_url))}/?$ ${ORIGIN}${r.new_url} [R=301,L,NE]`).join("\n")}

# 2) Deliberately removed pages -> real 410 (never redirected to the home page).
${gone.map((r) => `RewriteRule ^${reEsc(stripSlash(r.old_url))}/?$ - [G,L]`).join("\n")}
<If "%{REQUEST_URI} =~ m#^/(${[...WRITTEN].map((p) => reEsc(stripSlash(p))).join("|")})/?$#">
  ErrorDocument 410 /410-yazili-ceviri.html
</If>
<Else>
  ErrorDocument 410 /410.html
</Else>

# 3) One canonical host: https://www.cince-tercuman.com
RewriteCond %{HTTPS} !=on [OR]
RewriteCond %{HTTP_HOST} !^www\\.cince-tercuman\\.com$ [NC]
RewriteRule ^ ${ORIGIN}%{REQUEST_URI} [R=301,L,NE]

# 4) Directory URLs without the trailing slash -> slash version (one hop).
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME}/index.html -f
RewriteRule ^(.+[^/])$ ${ORIGIN}/$1/ [R=301,L,NE]

# 5) Real 404 for everything else (no SPA fallback to index.html).
ErrorDocument 404 /404.html

# 6) ES modules need a JavaScript MIME type for the contact form.
AddType text/javascript .js .mjs
AddType font/woff2 .woff2
`;

  const netlify = `${header("#")}
# Netlify / Cloudflare Pages format. Güzel Hosting does NOT read this file.
${moves.map((r) => `${r.old_url}  ${r.new_url}  301!`).join("\n")}
${gone.map((r) => `${r.old_url}  ${WRITTEN.has(r.old_url) ? "/410-yazili-ceviri.html" : "/410.html"}  410!`).join("\n")}
/*  /404.html  404
`;

  const nginx = `${header("#")}
# nginx server block sample.
server {
  listen 80;
  listen 443 ssl;
  server_name cince-tercuman.com www.cince-tercuman.com;
  if ($host != "www.cince-tercuman.com") { return 301 ${ORIGIN}$request_uri; }
  if ($scheme != "https") { return 301 ${ORIGIN}$request_uri; }

  root /var/www/cince-tercuman/dist;
  index index.html;
  types { text/javascript js mjs; font/woff2 woff2; text/css css; text/html html; application/xml xml; text/plain txt; image/svg+xml svg; }

${moves.map((r) => `  location ~ ^${reEsc(r.old_url.replace(/\/$/, ""))}/?$ { return 301 ${ORIGIN}${r.new_url}; }`).join("\n")}
${gone.map((r) => `  location ~ ^${reEsc(r.old_url.replace(/\/$/, ""))}/?$ { error_page 410 ${WRITTEN.has(r.old_url) ? "/410-yazili-ceviri.html" : "/410.html"}; return 410; }`).join("\n")}

  location / { try_files $uri $uri/index.html =404; }
  error_page 404 /404.html;
}
`;
  return { "redirects/htaccess.sample": apache, "redirects/_redirects": netlify, "redirects/nginx.conf.sample": nginx };
}

async function main() {
  const out = render(await readMapping());
  const check = process.argv.includes("--check");
  let stale = 0;
  for (const [rel, text] of Object.entries(out)) {
    const p = join(ROOT, rel);
    if (check) {
      const cur = await readFile(p, "utf8").catch(() => "");
      if (cur !== text) { console.error(`stale: ${rel}`); stale++; }
    } else await writeFile(p, text);
  }
  if (check && stale) process.exit(1);
  if (!check) console.log(`Wrote ${Object.keys(out).length} host rule samples.`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main().catch((e) => { console.error(e); process.exit(1); });
